import { EdgeStoreProvider } from '@/lib/edgestore';
import './globals.css';
import { ModeToggle, ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Tabs } from './tabs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Source+Code+Pro:wght@200;300;400&display=swap" rel="stylesheet" />
      </head>

      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="m-6 flex flex-col gap-3">
            <div className="flex justify-center">
              <ModeToggle />
            </div>
            <Tabs />
            <EdgeStoreProvider basePath="/components/api/edgestore">
              {children}
            </EdgeStoreProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
