import { EdgeStoreProvider } from '@/lib/edgestore';
import './globals.css';
import { ModeToggle, ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Tabs } from './tabs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="m-6 flex flex-col gap-3">
            <div className="flex justify-center">
              <ModeToggle />
            </div>
            <Tabs />
            <EdgeStoreProvider basePath="/components/api/edgestore">
              {children}
            </EdgeStoreProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
