import { EdgeStoreProvider } from '@/lib/edgestore';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import { Tabs } from './tabs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, 'm-6')}>
        <Tabs />
        <EdgeStoreProvider basePath="/components/api/edgestore">
          {children}
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
