import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        slug: '/getting-started',
      },
      items: [
        'main/quick-start',
        'main/configuration',
        'main/backend-client',
        'main/utils',
        'main/error-handling',
        'main/logging',
        'main/llms-ai-ides',
        'main/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Components',
        slug: '/components',
      },
      items: [
        'components/image',
        'components/multi-image',
        'components/multi-file',
      ],
    },
    {
      type: 'category',
      label: 'Adapters',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Adapters',
        slug: '/adapters',
      },
      items: [
        'adapters/next-adapter',
        'adapters/express-adapter',
        'adapters/tanstack-start-adapter',
      ],
    },
    {
      type: 'category',
      label: 'Providers',
      collapsed: false,
      items: [
        'providers/edgestore',
        'providers/aws',
        'providers/azure',
        'providers/custom',
      ],
    },
  ],
};

export default sidebars;
